apiVersion: apps/v1
kind: Deployment
metadata:
  name: pft-finance-tracker
  namespace: default
  labels:
    app.kubernetes.io/name: finance-tracker
    app.kubernetes.io/instance: pft
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: finance-tracker
      app.kubernetes.io/instance: pft
  template:
    metadata:
      labels:
        app.kubernetes.io/name: finance-tracker
        app.kubernetes.io/instance: pft
    spec:
      containers:
        - name: finance-tracker
          image: personal-finance-tracker:ci
          imagePullPolicy: Never
          ports:
            - containerPort: 80
