apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finance-tracker.fullname" . }}-config
  labels:
    {{- include "finance-tracker.labels" . | nindent 4 }}
data:
  DATA_PATH: {{ .Values.config.dataPath | quote }}

