replicaCount: 1

image:
  repository: yonid78/finance-tracker
  pullPolicy: IfNotPresent
  tag: "1.1"

service:
  type: NodePort
  port: 80
  nodePort: 30080

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

config:
  dataPath: "/app/json_data/finance_data.json"

secret:
  dbPassword: "myStrongPassword123"

cronjob:
  enabled: true
  schedule: "* * 1 * *"   

